### ISSUE TITLE
Связь mylyn и СППР + VA

### ISSUE THREAD

**Issue by DoublesunRUS** [marmyshev/edt-plugins#14]
Когда Vanessa Automation выполняет сценарные тесты, она фиксирует ошибки прохождения тестов. Сейчас ведется доработка VA, чтобы она эти ошибки фиксировала сразу, а не по окончанию тестов.
Далее необходимо чтобы эти ошибки сразу можно было загружать в СППР.
Необходимо написать коннектор для СППР к плагину Mylyn, чтобы ошибки СППР сразу отображались в EDT.

**Comment by marmyshev** [comment]
Кажется это похоже на идею https://github.com/marmyshev/edt-plugins/issues/1

**Comment by DoublesunRUS** [comment]
Да, я сразу не заметил что есть уже такая идея.
