### ISSUE TITLE
Внешний редактор кода

### ISSUE THREAD

**Issue by I03D** [marmyshev/edt-plugins#47]
Вроде бы есть всякие наборы подсветок для редакторов, а открыть код муторно. Либо скопировать, либо пересохранить, чтобы файл стал внешним. В общем, нужен более быстрый запуск. Как хотите: либо по сочетанию клавиш, либо мгновенно, по открытию в конфигураторе. Спасибо.

**Comment by marmyshev** [comment]
Спасибо и вам. Но ваша идея - вообще не понятная! Я все слова понимаю, но смысла проблемы которую вы хотите решить - не понимаю :)

Вы предлагаете сделать плагин к ЕДТ который что делает? Какую проблему решает?

Т.е. просто из "Проводника" открыть модуль в вашем любимом редакторе - это уже не модно? Ну т.е. поставьте себя на место какого-то гипотетического разработчика плагинов который бы захотел вам помочь - какой сценарий он должен реализовать и почему это надо делать?

Внешний редактор - какой именно? Sublime? Notepad++? VsCode? они и так умеют работать со структурой папок, зачем вам вообще ЕДТ тогда?

К тому же, можно в ЕДТ ассоциировать любой внешний редактор с типо файлов - и будет открываться по файлу (но не из навигатора 1С конечно)
